# Generated by Django 5.1.2 on 2024-10-27 07:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('role_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 27, 7, 50, 41, 76514, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=6)),
                ('admin_fname', models.CharField(max_length=255)),
                ('admin_lname', models.CharField(max_length=255)),
                ('admin_email', models.EmailField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 27, 7, 50, 41, 102600, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aa2000_admin.adminlevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aa2000_admin.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa2000_admin.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aa2000_admin.user')),
            ],
        ),
    ]
