# Generated by Django 5.1.2 on 2024-10-27 09:03

import aa2000_admin.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_photo',
            field=models.ImageField(default='admins/aa2000_icon.png', upload_to=aa2000_admin.models.admin_image_path),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 9, 3, 24, 655502, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 9, 3, 24, 620805, tzinfo=datetime.timezone.utc)),
        ),
    ]
