# Generated by Django 5.1.2 on 2024-10-27 13:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0002_admin_admin_photo_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 13, 27, 52, 976606, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aa2000_admin.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 13, 27, 52, 949392, tzinfo=datetime.timezone.utc)),
        ),
    ]
