# Generated by Django 5.1.2 on 2024-10-27 16:49

import aa2000_admin.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0003_alter_admin_created_at_alter_admin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('brand_logo', models.ImageField(default='brands/aa2000_icon.png', upload_to=aa2000_admin.models.brand_image_path)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 27, 16, 49, 1, 532282, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 16, 49, 1, 531280, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 16, 49, 1, 531280, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BrandDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_description_1', models.TextField(blank=True)),
                ('brand_description_2', models.TextField(blank=True)),
                ('brand_image_1', models.ImageField(blank=True, upload_to=aa2000_admin.models.brand_image_path)),
                ('brand_image_2', models.ImageField(blank=True, upload_to=aa2000_admin.models.brand_image_path)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 27, 16, 49, 1, 532282, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aa2000_admin.brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aa2000_admin.system'),
        ),
    ]
