# Generated by Django 5.1.2 on 2024-10-27 18:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0005_rename_slug_brand_brand_slug_alter_admin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 18, 40, 45, 224273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 18, 40, 45, 225273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='branddetail',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_details', to='aa2000_admin.brand'),
        ),
        migrations.AlterField(
            model_name='branddetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 18, 40, 45, 225273, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 18, 40, 45, 223268, tzinfo=datetime.timezone.utc)),
        ),
    ]
