# Generated by Django 5.1.2 on 2024-10-28 01:37

import aa2000_admin.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0006_alter_admin_created_at_alter_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 1, 37, 5, 394703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 1, 37, 5, 394703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='branddetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 1, 37, 5, 395719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 1, 37, 5, 393720, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 1, 37, 5, 395719, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_system', to='aa2000_admin.system')),
            ],
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_feature', models.TextField()),
                ('key_feature_image', models.ImageField(blank=True, upload_to=aa2000_admin.models.product_image_path)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 1, 37, 5, 396721, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='aa2000_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productCategory_system', to='aa2000_admin.system')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(blank=True, upload_to=aa2000_admin.models.product_image_path)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 1, 37, 5, 396721, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_descriptions', to='aa2000_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aa2000_admin.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aa2000_admin.productcategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='aa2000_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(default='products/aa2000_icon.png', upload_to=aa2000_admin.models.product_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='aa2000_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='TechSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_spec', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 1, 37, 5, 396721, tzinfo=datetime.timezone.utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tectSpec', to='aa2000_admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='TechSpecDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_spec_name', models.CharField(max_length=200)),
                ('tech_spec_value', models.CharField(max_length=200)),
                ('tech_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_spec_details', to='aa2000_admin.techspec')),
            ],
        ),
    ]
