# Generated by Django 5.1.2 on 2024-10-28 02:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0007_alter_admin_created_at_alter_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_brand', to='aa2000_admin.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_category', to='aa2000_admin.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 39, 23, 612462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 39, 23, 613480, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='branddetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 39, 23, 613480, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='keyfeature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 39, 23, 614478, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 39, 23, 614478, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 39, 23, 614478, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='techspec',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 39, 23, 615478, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 39, 23, 611480, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
