# Generated by Django 5.1.2 on 2024-10-29 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0009_alter_admin_created_at_alter_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 4, 16, 11, 156051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 4, 16, 11, 157051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='branddetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 4, 16, 11, 157051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='keyfeature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 4, 16, 11, 159052, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 4, 16, 11, 158052, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 4, 16, 11, 159052, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='techspec',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 4, 16, 11, 159052, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 4, 16, 11, 155051, tzinfo=datetime.timezone.utc)),
        ),
    ]
