# Generated by Django 5.1.2 on 2024-10-29 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0011_alter_admin_created_at_alter_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 5, 20, 17, 456476, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 5, 20, 17, 456476, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='branddetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 5, 20, 17, 457456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='keyfeature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 5, 20, 17, 459373, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 5, 20, 17, 458452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 5, 20, 17, 458452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='techspec',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 5, 20, 17, 459373, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 5, 20, 17, 454373, tzinfo=datetime.timezone.utc)),
        ),
    ]
