# Generated by Django 5.1.2 on 2024-11-03 10:17

import aa2000_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0015_job_jobcompensationbenefits_jobdescriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_image',
            field=models.ImageField(default='jobs/aa2000_icon.png', upload_to=aa2000_admin.models.job_image_path),
        ),
    ]
