# Generated by Django 5.1.2 on 2024-11-04 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0018_article_articlecontent_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
