# Generated by Django 5.1.2 on 2024-11-04 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0019_author_author_description_author_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='aa2000_admin.article'),
        ),
    ]
