# Generated by Django 5.1.2 on 2024-11-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0021_action_entity_adminactivitylogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='action',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='modified_at',
        ),
    ]
