# Generated by Django 5.1.2 on 2024-11-05 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0022_remove_action_created_at_remove_action_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylogs',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_on_activity', to='aa2000_admin.admin'),
        ),
    ]
