# Generated by Django 5.1.2 on 2024-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0023_alter_adminactivitylogs_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylogs',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
