# Generated by Django 5.1.2 on 2024-11-08 07:46

import aa2000_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0024_adminactivitylogs_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_cover',
            field=models.ImageField(default='articles/aa2000_icon.png', upload_to=aa2000_admin.models.article_image_path),
        ),
    ]
