# Generated by Django 5.1.2 on 2024-11-13 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0028_generalvisit_entityvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvisit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='generalvisit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
