# Generated by Django 5.1.2 on 2024-11-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0029_alter_entityvisit_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvisit',
            name='visitor_id',
            field=models.CharField(default='visitor_00000', max_length=255, unique=True),
        ),
    ]
