# Generated by Django 5.1.2 on 2024-11-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa2000_admin', '0032_alter_generalvisit_visitor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityvisit',
            name='visitor_id',
            field=models.CharField(default='visitor_00000', max_length=255),
        ),
    ]
